# Collector specific configuration
base_url: "https://api.ipcinfo.org"
showcase_url: "https://www.ipcinfo.org/ipc-country-analysis/en/?country="
ch_showcase_url: "https://www.ipcinfo.org/ch/en/"
long_hxltags:
  "Date of analysis": "#date+analysis"
  "Country": "#country+code"
  "Level 1": "#loc+level1"
  "Area": "#loc+area"
  "Total country population": "#population"
  "Validity period": "#period+v_ipc"
  "From": "#date+start"
  "To": "#date+end"
  "Phase": "#severity+v_ipc"
  "Number": "#affected+num"
  "Percentage": "#affected+pct"
wide_hxltags:
  "Date of analysis": "#date+analysis"
  "Country": "#country+code"
  "Level 1": "#loc+level1"
  "Area": "#loc+area"
  "Total country population": "#population"
  "Current from": "#date+start+current"
  "Current to": "#date+end+current"
  "Population analyzed current": "#affected+num+ipc+current+total"
  "Phase 3+ number current": "#affected+num+ipc+current+p3plus"
  "Phase 3+ percentage current": "#affected+pct+ipc+current+p3plus"
  "Phase 1 number current": "#affected+num+ipc+current+phase1"
  "Phase 1 percentage current": "#affected+pct+ipc+current+phase1"
  "Phase 2 number current": "#affected+num+ipc+current+phase2"
  "Phase 2 percentage current": "#affected+pct+ipc+current+phase2"
  "Phase 3 number current": "#affected+num+ipc+current+phase3"
  "Phase 3 percentage current": "#affected+pct+ipc+current+phase3"
  "Phase 4 number current": "#affected+num+ipc+current+phase4"
  "Phase 4 percentage current": "#affected+pct+ipc+current+phase4"
  "Phase 5 number current": "#affected+num+ipc+current+phase5"
  "Phase 5 percentage current": "#affected+pct+ipc+current+phase5"
  "First projection from": "#date+start+first_projection"
  "First projection to": "#date+end+first_projection"
  "Population analyzed first projection": "#affected+num+ipc+first_projection+total"
  "Phase 3+ number first projection": "#affected+num+ipc+first_projection+p3plus"
  "Phase 3+ percentage first projection": "#affected+pct+ipc+first_projection+p3plus"
  "Phase 1 number first projection": "#affected+num+ipc+first_projection+phase1"
  "Phase 1 percentage first projection": "#affected+pct+ipc+first_projection+phase1"
  "Phase 2 number first projection": "#affected+num+ipc+first_projection+phase2"
  "Phase 2 percentage first projection": "#affected+pct+ipc+first_projection+phase2"
  "Phase 3 number first projection": "#affected+num+ipc+first_projection+phase3"
  "Phase 3 percentage first projection": "#affected+pct+ipc+first_projection+phase3"
  "Phase 4 number first projection": "#affected+num+ipc+first_projection+phase4"
  "Phase 4 percentage first projection": "#affected+pct+ipc+first_projection+phase4"
  "Phase 5 number first projection": "#affected+num+ipc+first_projection+phase5"
  "Phase 5 percentage first projection": "#affected+pct+ipc+first_projection+phase5"
  "Second projection from": "#date+start+second_projection"
  "Second projection to": "#date+end+second_projection"
  "Population analyzed second projection": "#affected+num+ipc+second_projection+total"
  "Phase 3+ number second projection": "#affected+num+ipc+second_projection+p3plus"
  "Phase 3+ percentage second projection": "#affected+pct+ipc+second_projection+p3plus"
  "Phase 1 number second projection": "#affected+num+ipc+second_projection+phase1"
  "Phase 1 percentage second projection": "#affected+pct+ipc+second_projection+phase1"
  "Phase 2 number second projection": "#affected+num+ipc+second_projection+phase2"
  "Phase 2 percentage second projection": "#affected+pct+ipc+second_projection+phase2"
  "Phase 3 number second projection": "#affected+num+ipc+second_projection+phase3"
  "Phase 3 percentage second projection": "#affected+pct+ipc+second_projection+phase3"
  "Phase 4 number second projection": "#affected+num+ipc+second_projection+phase4"
  "Phase 4 percentage second projection": "#affected+pct+ipc+second_projection+phase4"
  "Phase 5 number second projection": "#affected+num+ipc+second_projection+phase5"
  "Phase 5 percentage second projection": "#affected+pct+ipc+second_projection+phase5"
