# Collector specific configuration
base_url: "https://api.ipcinfo.org"
long_hxltags:
  analysis_date: "#date+analysis"
  country_iso3: "#country+code"
  level1_name: "#loc+level1"
  area: "#loc+area"
  population: "#population"
  projection: "#meta+projection"
  period_start: "#date+start"
  period_end: "#date+end"
  phase: "#meta+phase"
  number_affected: "#affected+num+ipc"
  percentage_affected: "#affected+pct+ipc"
wide_hxltags:
  analysis_date: "#date+analysis"
  country_iso3: "#country+code"
  level1_name: "#loc+level1"
  area: "#loc+area"
  population: "#population"
  period_start: "#date+start+current"
  period_end: "#date+end+current"
  affected_population: "#affected+num+ipc+current+total"
  p3plus_population: "#affected+num+ipc+current+p3plus"
  p3plus_percentage: "#affected+pct+ipc+current+p3plus"
  phase1_population: "#affected+num+ipc+current+phase1"
  phase1_percentage: "#affected+pct+ipc+current+phase2"
  phase2_population: "#affected+num+ipc+current+phase1"
  phase2_percentage: "#affected+pct+ipc+current+phase2"
  phase3_population: "#affected+num+ipc+current+phase3"
  phase3_percentage: "#affected+pct+ipc+current+phase3"
  phase4_population: "#affected+num+ipc+current+phase4"
  phase4_percentage: "#affected+pct+ipc+current+phase4"
  phase5_population: "#affected+num+ipc+current+phase5"
  phase5_percentage: "#affected+pct+ipc+current+phase5"
  period_start_projected: "#date+start+projected"
  period_end_projected: "#date+end+projected"
  affected_population_projected: "#affected+num+ipc+projected+total"
  p3plus_population_projected: "#affected+num+ipc+projected+p3plus"
  p3plus_percentage_projected: "#affected+pct+ipc+projected+p3plus"
  phase1_population_projected: "#affected+num+ipc+projected+phase1"
  phase1_percentage_projected: "#affected+pct+ipc+projected+phase2"
  phase2_population_projected: "#affected+num+ipc+projected+phase1"
  phase2_percentage_projected: "#affected+pct+ipc+projected+phase2"
  phase3_population_projected: "#affected+num+ipc+projected+phase3"
  phase3_percentage_projected: "#affected+pct+ipc+projected+phase3"
  phase4_population_projected: "#affected+num+ipc+projected+phase4"
  phase4_percentage_projected: "#affected+pct+ipc+projected+phase4"
  phase5_population_projected: "#affected+num+ipc+projected+phase5"
  phase5_percentage_projected: "#affected+pct+ipc+projected+phase5"
