# Collector specific configuration
base_url: "https://api.ipcinfo.org"
long_hxltags:
  "Date of analysis": "#date+analysis"
  "Country": "#country+code"
  "Level 1": "#loc+level1"
  "Area": "#loc+area"
  "Total country population": "#population"
  "Validity period": "#period+v_ipc"
  "From": "#date+start"
  "To": "#date+end"
  "Phase": "#severity+v_ipc"
  "Number": "#affected+num"
  "Percentage": "#affected+pct"
wide_hxltags:
  "Date of analysis": "#date+analysis"
  "Country": "#country+code"
  "Level 1": "#loc+level1"
  "Area": "#loc+area"
  "Total country population": "#population"
  "Current from": "#date+start+current"
  "Current to": "#date+end+current"
  "Population analyzed current": "#affected+num+ipc+current+total"
  "Phase 3+ number current": "#affected+num+ipc+current+p3plus"
  "Phase 3+ percentage current": "#affected+pct+ipc+current+p3plus"
  "Phase 1 number current": "#affected+num+ipc+current+phase1"
  "Phase 1 percentage current": "#affected+pct+ipc+current+phase2"
  "Phase 2 number current": "#affected+num+ipc+current+phase1"
  "Phase 2 percentage current": "#affected+pct+ipc+current+phase2"
  "Phase 3 number current": "#affected+num+ipc+current+phase3"
  "Phase 3 percentage current": "#affected+pct+ipc+current+phase3"
  "Phase 4 number current": "#affected+num+ipc+current+phase4"
  "Phase 4 percentage current": "#affected+pct+ipc+current+phase4"
  "Phase 5 number current": "#affected+num+ipc+current+phase5"
  "Phase 5 percentage current": "#affected+pct+ipc+current+phase5"
  "Projection from": "#date+start+projected"
  "Projection to": "#date+end+projected"
  "Population analyzed projection": "#affected+num+ipc+projected+total"
  "Phase 3+ number projection": "#affected+num+ipc+projected+p3plus"
  "Phase 3+ percentage projection": "#affected+pct+ipc+projected+p3plus"
  "Phase 1 number projection": "#affected+num+ipc+projected+phase1"
  "Phase 1 percentage projection": "#affected+pct+ipc+projected+phase2"
  "Phase 2 number projection": "#affected+num+ipc+projected+phase1"
  "Phase 2 percentage projection": "#affected+pct+ipc+projected+phase2"
  "Phase 3 number projection": "#affected+num+ipc+projected+phase3"
  "Phase 3 percentage projection": "#affected+pct+ipc+projected+phase3"
  "Phase 4 number projection": "#affected+num+ipc+projected+phase4"
  "Phase 4 percentage projection": "#affected+pct+ipc+projected+phase4"
  "Phase 5 number projection": "#affected+num+ipc+projected+phase5"
  "Phase 5 percentage projection": "#affected+pct+ipc+projected+phase5"
  "Second projection from": "#date+start+second_projected"
  "Second projection to": "#date+end+second_projected"
  "Population analyzed second projection": "#affected+num+ipc+second_projected+total"
  "Phase 3+ number second projection": "#affected+num+ipc+second_projected+p3plus"
  "Phase 3+ percentage second projection": "#affected+pct+ipc+second_projected+p3plus"
  "Phase 1 number second projection": "#affected+num+ipc+second_projected+phase1"
  "Phase 1 percentage second projection": "#affected+pct+ipc+second_projected+phase2"
  "Phase 2 number second projection": "#affected+num+ipc+second_projected+phase1"
  "Phase 2 percentage second projection": "#affected+pct+ipc+second_projected+phase2"
  "Phase 3 number second projection": "#affected+num+ipc+second_projected+phase3"
  "Phase 3 percentage second projection": "#affected+pct+ipc+second_projected+phase3"
  "Phase 4 number second projection": "#affected+num+ipc+second_projected+phase4"
  "Phase 4 percentage second projection": "#affected+pct+ipc+second_projected+phase4"
  "Phase 5 number second projection": "#affected+num+ipc+second_projected+phase5"
  "Phase 5 percentage second projection": "#affected+pct+ipc+second_projected+phase5"
