# Collector specific configuration
base_url: "https://api.ipcinfo.org"
showcase_url: "https://www.ipcinfo.org/ipc-country-analysis/en/?country="
ch_showcase_url: "https://www.ipcinfo.org/ch/en/"
long_hxltags:
  "Date of analysis": "#date+analysis"
  "Country": "#country+code"
  "Level 1": "#loc+level1"
  "Area": "#loc+area"
  "Total country population": "#population"
  "Validity period": "#period+v_ipc"
  "From": "#date+start"
  "To": "#date+end"
  "Phase": "#severity+v_ipc"
  "Number": "#affected+num"
  "Percentage": "#affected+pct"
wide_hxltags:
  "Date of analysis": "#date+analysis"
  "Country": "#country+code"
  "Level 1": "#loc+level1"
  "Area": "#loc+area"
  "Total country population": "#population"
  "Current from": "#date+start+current"
  "Current to": "#date+end+current"
  "Population analyzed current": "#affected+num+ipc+current+total"
  "Phase 3+ number current": "#affected+num+ipc+current+p3plus"
  "Phase 3+ percentage current": "#affected+pct+ipc+current+p3plus"
  "Phase 1 number current": "#affected+num+ipc+current+phase1"
  "Phase 1 percentage current": "#affected+pct+ipc+current+phase1"
  "Phase 2 number current": "#affected+num+ipc+current+phase2"
  "Phase 2 percentage current": "#affected+pct+ipc+current+phase2"
  "Phase 3 number current": "#affected+num+ipc+current+phase3"
  "Phase 3 percentage current": "#affected+pct+ipc+current+phase3"
  "Phase 4 number current": "#affected+num+ipc+current+phase4"
  "Phase 4 percentage current": "#affected+pct+ipc+current+phase4"
  "Phase 5 number current": "#affected+num+ipc+current+phase5"
  "Phase 5 percentage current": "#affected+pct+ipc+current+phase5"
  "First projection from": "#date+start+first_projection"
  "First projection to": "#date+end+first_projection"
  "Population analyzed first projection": "#affected+num+ipc+first_projection+total"
  "Phase 3+ number first projection": "#affected+num+ipc+first_projection+p3plus"
  "Phase 3+ percentage first projection": "#affected+pct+ipc+first_projection+p3plus"
  "Phase 1 number first projection": "#affected+num+ipc+first_projection+phase1"
  "Phase 1 percentage first projection": "#affected+pct+ipc+first_projection+phase1"
  "Phase 2 number first projection": "#affected+num+ipc+first_projection+phase2"
  "Phase 2 percentage first projection": "#affected+pct+ipc+first_projection+phase2"
  "Phase 3 number first projection": "#affected+num+ipc+first_projection+phase3"
  "Phase 3 percentage first projection": "#affected+pct+ipc+first_projection+phase3"
  "Phase 4 number first projection": "#affected+num+ipc+first_projection+phase4"
  "Phase 4 percentage first projection": "#affected+pct+ipc+first_projection+phase4"
  "Phase 5 number first projection": "#affected+num+ipc+first_projection+phase5"
  "Phase 5 percentage first projection": "#affected+pct+ipc+first_projection+phase5"
  "Second projection from": "#date+start+second_projection"
  "Second projection to": "#date+end+second_projection"
  "Population analyzed second projection": "#affected+num+ipc+second_projection+total"
  "Phase 3+ number second projection": "#affected+num+ipc+second_projection+p3plus"
  "Phase 3+ percentage second projection": "#affected+pct+ipc+second_projection+p3plus"
  "Phase 1 number second projection": "#affected+num+ipc+second_projection+phase1"
  "Phase 1 percentage second projection": "#affected+pct+ipc+second_projection+phase1"
  "Phase 2 number second projection": "#affected+num+ipc+second_projection+phase2"
  "Phase 2 percentage second projection": "#affected+pct+ipc+second_projection+phase2"
  "Phase 3 number second projection": "#affected+num+ipc+second_projection+phase3"
  "Phase 3 percentage second projection": "#affected+pct+ipc+second_projection+phase3"
  "Phase 4 number second projection": "#affected+num+ipc+second_projection+phase4"
  "Phase 4 percentage second projection": "#affected+pct+ipc+second_projection+phase4"
  "Phase 5 number second projection": "#affected+num+ipc+second_projection+phase5"
  "Phase 5 percentage second projection": "#affected+pct+ipc+second_projection+phase5"
hapi_hxltags:
  location_code: "#country+code"
  has_hrp: "#meta+has_hrp"
  in_gho: "#meta+in_gho"
  provider_admin1_name: "#adm1+name+provider"
  provider_admin2_name: "#adm2+name+provider"
  admin1_code: "#adm1+code"
  admin1_name: "#adm1+name"
  admin2_code: "#adm2+code"
  admin2_name: "#adm2+name"
  admin_level: "#adm+level"
  ipc_phase: "#severity+v_ipc"
  ipc_type: "#period+v_ipc"
  population_in_phase: "#affected+num"
  population_fraction_in_phase: "#affected+pct"
  reference_period_start: "#date+start"
  reference_period_end: "#date+end"
  dataset_hdx_id: "#meta+dataset_id"
  resource_hdx_id: "#meta+resource_id"
  warning: "#meta+warning"
  error: "#meta+error"
hapi_resource:
  name: "Global Food Security, Nutrition & Poverty: Food Security"
  description: "Food Security data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/food_security_nutrition_and_poverty/#food-security) for more information"
hapi_adm_matching:
  # The patterns ensure removal of non-admin units. These are where admin units
  # have been split to suit the org's own purposes, for example into
  # ural/urban, (1)...(5), _1..._4, or where the org reports data on a
  # subset of the population like idps/refugees/returnees
  adm_ignore_patterns:
    - " urban"
    - " rural"
    - "rural "
    - "(1)"
    - "(2)"
    - "(3)"
    - "(4)"
    - "(5)"
    - "_1"
    - "_2"
    - "_3"
    - "_4"
    - "idp"
    - "refugee"
    - "returnee"
    - " cluster "
    - " commune "
    - " accessible"

  # This is where all "Areas" are non-admin units and so there is only admin 1
  # data available in "Level 1"
  adm1_only:
    - "DJI"
    - "HTI"
    - "MMR"
    - "SOM"
    - "ZAF"

  # This is where "Level 1" is blank and there is only admin 2 data available
  # in "Area" (usually blank "Level 1" means "Area" is admin 1 rather than 2)
  # In this case ignore admin one data
  adm2_only:
    - "DOM"
    - "MWI"
    - "PSE"
    - "TZA"
    - "UGA"

  # This is where "Level 1" is blank and there is only admin 2 data available
  # in "Area" (usually blank "Level 1" means "Area" is admin 1 rather than 2)
  adm2_only_include_adm1:
    - "MDG"
    - "SEN"

  # This is where there is only admin 2 data available in "Level 1" whether
  # "Area" is blank or not
  adm2_in_level1:
    - "LBN"

  # This is where "Level 1" is non-admin units and so there is only admin 1
  # data available in "Area"
  adm1_in_area:
    - "KEN"

  # The exceptions below were picked up from the logging which outputs all the
  # fuzzy matches
  admin1:
    admin_name_mappings:
      "CAF|Ouham-Fafa": "CF32"
      "CMR|Far-North": "CM004"
      "CMR|West": "CM008"
      "DJI|Djibouti Ville": "DJ04"
      "GHA|North east": "GH09"
      "GMB|Basse": "GM02"
      "GMB|Brikama": "GM03"
      "GMB|Janjanbureh": "GM04"
      "GMB|Kerewan": "GM06"
      "GMB|Kuntaur": "GM07"
      "GMB|Mansa konko": "GM08"
      "HND|Fco. Morazán": "HN08"
      "HTI|Nord-Ouest": "HT09"
      "HTI|Sud": "HT07"
      "KEN|Embu (Mbeere)": "KE014"
      "KEN|Lamu county": "KE005"
      "MDG|Fitovivany": "MG23"
      "MOZ|Maputo Provincia": "MZ05"
      "MOZ|Provincia de Maputo": "MZ05"
      "NAM|Khomas Region": "NA06"
      "SLE|Western Area": "SL04"
      "SOM|Juba dhexe": "SO27"
      "SOM|Juba hoose": "SO28"
      "SOM|Shabelle dhexe": "SO21"
      "SOM|Shabelle hoose": "SO23"
      "YEM|Amanat Al Asimah": "YE13"
      "YEM|Amanat al asimah": "YE13"

    admin_name_replacements:
      "ZMB| province": ""

    admin_fuzzy_dont:
      - "distrito central"
      - "others"
      - "prefectures"
      - "AGO|cahama"
      - "AGO|cuanhama"
      - "AGO|matala"
      - "CAF|haut-oubangui"
      - "CAF|kagas"
      - "CAF|yadé"
      - "HND|occidente"
      - "KEN|kibra"
      - "KEN|mukuru"
      - "KEN|mathare"
      - "KEN|kondele"
      - "KEN|kangemi"
      - "KEN|kawangware"
      - "KEN|bangladesh"
      - "KEN|kayole"
      - "KEN|dandora"
      - "KEN|githurai"
      - "KEN|mwembe tayari"
      - "KEN|obunga"
      - "MRT|nouakchott"
      - "PAK|khyber"
      - "YEM|yemen"

  admin2:
    admin_name_mappings:
      "AGO|Cahama": "AO08062"
      "AGO|Município dos Gambos (ex-chiange)": "AO09073"
      "AGO|Mocamedes": "AO16139"
      "BGD|Barishal": "BD1006"
      "BGD|Chattogram": "BD2015"
      "BGD|Jashore": "BD4041"
      "BGD|Bogura": "BD5010"
      "BGD|Moulvibazar": "BD6058"
      "BFA|Kouritenga": "BF4803"
      "BFA|Komonjdjari": "BF5203"
      "DOM|Bahoruco": "DOM0603"
      "DOM|Santiago": "DOM0125"
      "ETH|Zone 1 (awsi rasu)": "ET0201"
      "ETH|Zone 2 (kilbet rasu)": "ET0202"
      "ETH|Zone 3 (gabi rasu)": "ET0203"
      "ETH|Zone 4 (fantana rasu)": "ET0204"
      "ETH|Zone 5 (hari rasu)": "ET0205"
      "LBN|Bent jbell": "LB41"
      "LBN|Jbell": "LB34"
      "LBN|Zahie": "LB25"
      "MDG|Manakara-sud": "MG23210"
      "MDG|Toliara II": "MG51520"
      "MDG|Toliara 2": "MG51520"
      "MDG|Tsiombe": "MG52514"
      "MDG|Amboasary-sud": "MG53519"
      "MLI|Baroueli": "ML0401"
      "MOZ|Xai-xai city": "MZ0207"
      "MOZ|Mandlakazi": "MZ0211"
      "MOZ|Inhambane city": "MZ0301"
      "MOZ|Maxixe city": "MZ0310"
      "MOZ|Cidade de Maxixe": "MZ0310"
      "MOZ|Chimoio city": "MZ0402"
      "MOZ|Matola city": "MZ0502"
      "MOZ|Cidade de Matola": "MZ0502"
      "MOZ|Nacala Porto": "MZ0719"
      "MOZ|Nacala-porto": "MZ0719"
      "MOZ|Nampula city": "MZ0702"
      "MOZ|Lichinga city": "MZ0802"
      "MOZ|Cidade de Beira": "MZ0906"
      "MOZ|Tete city": "MZ1006"
      "MOZ|Chuita": "MZ1005"
      "MOZ|Zumbo": "MZ1015"
      "MOZ|Quelimane": "MZ1103"
      "MOZ|Molocue": "MZ1101"
      "MRT|Bassikounou": "MR012"
      "MRT|Djigueni": "MR013"
      "MRT|N'beiket lehouach": "MR017"
      "MRT|Timbedgha": "MR016"
      "MRT|Aioun el atrous": "MR021"
      "MRT|Koubenni": "MR022"
      "MRT|Twil": "MR025"
      "MRT|Guerrou": "MR033"
      "MRT|Kankossa": "MR034"
      "MRT|Lexeiba": "MR045"
      "MRT|Monguel": "MR044"
      "MRT|Male": "MR056"
      "MRT|Magta lahjar": "MR054"
      "MRT|Maghta lahjar": "MR054"
      "MRT|Boutilimitt": "MR061"
      "MRT|Keur macene": "MR062"
      "MRT|Keur-macene": "MR062"
      "MRT|Chinguity": "MR073"
      "MRT|Tichitt": "MR092"
      "MRT|Tijigja": "MR093"
      "MRT|Ould yenge": "MR101"
      "MRT|Selibabi": "MR102"
      "MRT|Bir moghrein": "MR111"
      "MRT|Bir mogrein": "MR111"
      "MRT|F'derick": "MR112"
      "MRT|F'derik": "MR112"
      "MRT|Zoueratt": "MR113"
      "MWI|Nkhata bay": "MW103"
      "MWI|Chikhwawa": "MW310"
      "NGA|Munya": "NG027018"
      "NGA|Pailoro": "NG027019"
      "PAK|Dera Ismail Khan": "PK509"
      "PAK|Qambar Shahdadkot": "PK709"
      "PAK|Shaheed Benazirabad": "PK719"
      "PAK|Umerkot": "PK728"
      "PSE|Rafah Governorate": "PS0275"
      "SDN|Al leit": "SD02169"
      "SDN|El daein": "SD05142"
      "SDN|Janub aj jazirah": "SD15031"
      "SDN|Sharg aj jazirah": "SD15033"
      "SEN|Medina yoroufoula": "SN0702"
      "SEN|Tivaoune": "SN1303"
      "SLE|Falaba": "SL0206"
      "SSD|Raga": "SS0902"
      "TCD|Dodje": "TCD0802"
      "TCD|Barh signaka": "TCD0403"
      "TCD|Fittri": "TCD0103"
      "TCD|Am-djarass": "TCD2001"
      "TGO|Kpendial- Ouest": "TG0513"
      "TGO|Tandjouare": "TG0515"
      "TZA|Bahi DC": "TZ0106"
      "TZA|Musoma DC": "TZ2005"
      "TZA|Korogwe DC": "TZ0402"
      "TZA|Korogwe TC": "TZ0409"
      "TZA|Handeni TC": "TZ0406"
      "TZA|Handeni DC": "TZ0410"
      "TZA|Mkoani district": "TZ5502"
      "YEM|Al udayn": "YE1111"
      "YEM|Al dhihar": "YE1119"
      "YEM|As sayyani": "YE1115"
      "YEM|Far al udayn": "YE1110"
      "YEM|Hazm al udayn": "YE1109"
      "YEM|Hubaysh": "YE1108"
      "YEM|Al wade'a": "YE1208"
      "YEM|Khanfir": "YE1211"
      "YEM|Rasad": "YE1206"
      "YEM|Zingibar": "YE1210"
      "YEM|Al malagim": "YE1420"
      "YEM|Na'man": "YE1401"
      "YEM|Radman al awad": "YE1412"
      "YEM|Al  mukha": "YE1505"
      "YEM|Al wazi'iyah": "YE1515"
      "YEM|Jabal habashy": "YE1508"
      "YEM|Mashra'a wa hadnan": "YE1509"
      "YEM|Salh": "YE1519"
      "YEM|Sama": "YE1523"
      "YEM|Al khalq": "YE1609"
      "YEM|Al maton": "YE1606"
      "YEM|Bart al anan": "YE1610"
      "YEM|Khabb wa ash sha'af": "YE1601"
      "YEM|Aflah ash shawm": "YE1710"
      "YEM|Aslem": "YE1712"
      "YEM|Bani qa'is": "YE1724"
      "YEM|Haradh": "YE1702"
      "YEM|Kuhlan affar": "YE1718"
      "YEM|Qafl shamer": "YE1713"
      "YEM|Wadhrah": "YE1723"
      "YEM|Ad dahi": "YE1809"
      "YEM|Al garrahi": "YE1825"
      "YEM|Al hajjaylah": "YE1811"
      "YEM|Al khawkhah": "YE1820"
      "YEM|Alluheyah": "YE1802"
      "YEM|At tuhayat": "YE1826"
      "YEM|Az zaydiyah": "YE1807"
      "YEM|Bayt al faqiah": "YE1817"
      "YEM|Adh dhlia'ah": "YE1922"
      "YEM|Al qaf": "YE1903"
      "YEM|Ar raydah wa qusayar": "YE1913"
      "YEM|Brom mayfa": "YE1925"
      "YEM|Ghayl ba wazir": "YE1917"
      "YEM|Hagr as sai'ar": "YE1905"
      "YEM|Hajr": "YE1924"
      "YEM|Huraidhah": "YE1928"
      "YEM|Zamakh wa manwakh": "YE1904"
      "YEM|Anss": "YE2010"
      "YEM|Dawran aness": "YE2011"
      "YEM|Maghirib ans": "YE2004"
      "YEM|Mayfa'at anss": "YE2009"
      "YEM|Utmah": "YE2005"
      "YEM|Wusab al ali": "YE2006"
      "YEM|Ain": "YE2106"
      "YEM|Al talh": "YE2102"
      "YEM|Arma": "YE2104"
      "YEM|Dhar": "YE2101"
      "YEM|Mayfa'a": "YE2116"
      "YEM|Merkhah al ulya": "YE2108"
      "YEM|Merkhah as sufla": "YE2109"
      "YEM|Rudum": "YE2117"
      "YEM|Usaylan": "YE2105"
      "YEM|Al dhaher": "YE2207"
      "YEM|Kitaf wa al boqe'e": "YE2214"
      "YEM|Sa'adah": "YE2215"
      "YEM|Saqayn": "YE2209"
      "YEM|Al husn": "YE2315"
      "YEM|Attyal": "YE2313"
      "YEM|Bani dhabyan": "YE2314"
      "YEM|Khwlan": "YE2312"
      "YEM|Sanhan": "YE2305"
      "YEM|Al buraiqeh": "YE2404"
      "YEM|Al mansura": "YE2403"
      "YEM|Ash shaikh outhman": "YE2402"
      "YEM|Attawahi": "YE2405"
      "YEM|Craiter": "YE2407"
      "YEM|Critar - Sirah": "YE2407"
      "YEM|Al madaribah wa al arah": "YE2513"
      "YEM|Al maflahy": "YE2503"
      "YEM|Al milah": "YE2508"
      "YEM|Al qabbaytah": "YE2510"
      "YEM|Halimayn": "YE2506"
      "YEM|Yafa'a": "YE2502"
      "YEM|Medghal": "YE2603"
      "YEM|Al mahwait city": "YE2708"
      "YEM|Al mahwait": "YE2709"
      "YEM|Milhan": "YE2705"
      "YEM|Al ghaydah": "YE2804"
      "YEM|Huswain": "YE2809"
      "YEM|Shahan": "YE2801"
      "YEM|Al qaflah": "YE2904"
      "YEM|Bani suraim": "YE2920"
      "YEM|Dhi bin": "YE2909"
      "YEM|Habur zulaymah": "YE2908"
      "YEM|Iyal surayh": "YE2918"
      "YEM|Jabal iyal yazid": "YE2912"
      "YEM|Ad dhale'e": "YE3006"
      "YEM|Al hussein": "YE3005"
      "YEM|Qa'atabah": "YE3003"
      "YEM|Al jafariyah": "YE3106"
      "YEM|As salafiyah": "YE3102"
      "YEM|Bilad at ta'am": "YE3101"
      "YEM|Hidaybu": "YE3201"
      "YEM|Qulensya wa abd al kuri": "YE3202"
      "YEM|Ma'ain": "YE1308"
      "YEM|Ath'thaorah": "YE1309"
      "YEM|Az'zal": "YE1303"
      "YEM|As sabain": "YE1305"
      "YEM|Assafi'yah": "YE1304"
      "YEM|Shu'aub": "YE1302"
      "YEM|Al wahdah": "YE1306"
      "ZMB|Chiengi": "ZM104002"
      "ZMB|Milengi": "ZM104007"
      "ZMB|Lunte district": "ZM107011"
      "ZMB|Mushindano": "ZM108011"
      "ZMB|Chikankanta": "ZM109001"
      "ZWE|Muzarabani": "ZW1202"
      "ZWE|Uzumbamarambapfungwe": "ZW1309"
      "ZWE|Gokwenorth": "ZW1702"
      "ZWE|Gokwesouth": "ZW1703"

    admin_name_replacements:
      "COD|territoire de ": ""
      "COD|ville de ": ""
      "SSD| county": ""

    admin_fuzzy_dont:
      - "dawuro"  # wrong adm1 leads to incorrect mapping
      - "jariiban 2"
      - "kisenso"
      - "oodwweyne new"
      - "segen"
      - "GHA|ashanti"
      - "GHA|bono"
      - "GHA|bono east"
      - "GHA|central"
